### ISSUE TITLE
Concurrent map writes when using schema.ValidateBytes

### ISSUE THREAD

**Issue by chanchancl** [qri-io/jsonschema#76]
### What is your OS and version?
Ubuntu 16.04

### What version of qri are you using (`qri version`)?
0.1.1

### What version of Qri Desktop are you using?
no

### What did you do?
call schema.ValidateBytes method

### What happened?
program crashed due to concurrent map writes
2020-08-06T11:39:56.086850325Z fatal error: concurrent map writes
2020-08-06T11:39:56.098605569Z 
2020-08-06T11:39:56.098632512Z goroutine 220 [running]:
2020-08-06T11:39:56.098641557Z runtime.throw(0xb813f0, 0x15)
2020-08-06T11:39:56.098649007Z 	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc00088b328 sp=0xc00088b2f8 pc=0x433892
2020-08-06T11:39:56.098656586Z runtime.mapassign_faststr(0xa9a5c0, 0xc000486de0, 0xc00052b020, 0x4f, 0x0)
2020-08-06T11:39:56.098663451Z 	/usr/local/go/src/runtime/map_faststr.go:211 +0x3f7 fp=0xc00088b390 sp=0xc00088b328 pc=0x4131f7
2020-08-06T11:39:56.098670447Z vendor/github.com/qri-io/jsonschema.(*SchemaRegistry).Register(...)
2020-08-06T11:39:56.098677924Z 	/go/src/vendor/github.com/qri-io/jsonschema/schema_registry.go:73
2020-08-06T11:39:56.098685599Z vendor/github.com/qri-io/jsonschema.(*Schema).Register(0xc00044c5a0, 0xc00052ae40, 0x3c, 0xc0001b85f0)
2020-08-06T11:39:56.098693937Z 	/go/src/vendor/github.com/qri-io/jsonschema/schema.go:83 +0x26d fp=0xc00088b468 sp=0xc00088b390 pc=0x9ebbbd
2020-08-06T11:39:56.098717604Z vendor/github.com/qri-io/jsonschema.(*Properties).Register(0xc000524220, 0xc00052ae40, 0x3c, 0xc0001b85f0)
2020-08-06T11:39:56.098726471Z 	/go/src/vendor/github.com/qri-io/jsonschema/keywords_object.go:24 +0xb2 fp=0xc00088b4f8 sp=0xc00088b468 pc=0x9def72
2020-08-06T11:39:56.098734352Z vendor/github.com/qri-io/jsonschema.(*Schema).Register(0xc00044c300, 0xc00052ae40, 0x3c, 0xc0001b85f0)
2020-08-06T11:39:56.098741692Z 	/go/src/vendor/github.com/qri-io/jsonschema/schema.go:88 +0x173 fp=0xc00088b5d0 sp=0xc00088b4f8 pc=0x9ebac3
2020-08-06T11:39:56.098749364Z vendor/github.com/qri-io/jsonschema.(*Properties).Register(0xc0005241f0, 0xc0002934d0, 0x26, 0xc0001b85f0)
2020-08-06T11:39:56.098756244Z 	/go/src/vendor/github.com/qri-io/jsonschema/keywords_object.go:24 +0xb2 fp=0xc00088b660 sp=0xc00088b5d0 pc=0x9def72
2020-08-06T11:39:56.098764046Z vendor/github.com/qri-io/jsonschema.(*Schema).Register(0xc00044c2a0, 0xc0002934d0, 0x26, 0xc0001b85f0)
2020-08-06T11:39:56.098772722Z 	/go/src/vendor/github.com/qri-io/jsonschema/schema.go:88 +0x173 fp=0xc00088b738 sp=0xc00088b660 pc=0x9ebac3
2020-08-06T11:39:56.098780677Z vendor/github.com/qri-io/jsonschema.(*Schema).ValidateKeyword(0xc00044c2a0, 0xc91820, 0xc000046040, 0xc000174400, 0xa9bb20, 0xc000124e10)
2020-08-06T11:39:56.098788257Z 	/go/src/vendor/github.com/qri-io/jsonschema/schema.go:280 +0x8f fp=0xc00088b790 sp=0xc00088b738 pc=0x9ed31f
2020-08-06T11:39:56.098795651Z vendor/github.com/qri-io/jsonschema.(*Schema).Validate(0xc00044c2a0, 0xc91820, 0xc000046040, 0xa9bb20, 0xc000124e10, 0x0)
2020-08-06T11:39:56.098803042Z 	/go/src/vendor/github.com/qri-io/jsonschema/schema.go:260 +0x2ef fp=0xc00088b800 sp=0xc00088b790 pc=0x9ed18f
2020-08-06T11:39:56.098810559Z vendor/github.com/qri-io/jsonschema.(*Schema).ValidateBytes(0xc00044c2a0, 0xc91820, 0xc000046040, 0xc0003f8030, 0xe3, 0xe3, 0x4, 0xc00088ba40, 0x74004c, 0x119e8c0, ...)
2020-08-06T11:39:56.098818186Z 	/go/src/vendor/github.com/qri-io/jsonschema/schema.go:330 +0x16f fp=0xc00088b860 sp=0xc00088b800 pc=0x9ed95f

### What did you expect to happen?
Validate result.

**Comment by Arqu** [comment]
Thank you for the report. Will look into it over the next few days.

**Comment by Arqu** [comment]
@chanchancl If possible can you share a small reproducible example of the schema and input just to make things easier to test against while looking into it?

**Comment by chanchancl** [comment]
@Arqu  Sorry I can't provide the schema. Some questions I would ask instead.

Is this method schema.ValidateBytes thread-safe (in many goroutines)? 
Finally I add a lock for every schema checker.

But I have do some small tests to call this method in many different goroutine with small schema.
Never reproducing this problem again.(This problem was detected by others)

So I guess maybe this only happended when multi calls to this method with a big schema.

**Comment by Arqu** [comment]
Yeah, the implementation is not thread safe at the moment (mostly due to the global schema registry).
As such I'd avoid parallelizing this too much right now or at least introduce some locking mechanics to avoid it stepping on each others toes. 

Since the validation generally is fairly fast in many cases you won't even encounter this but given enough runs or a sufficiently large schema/input it should happen fairly regularly. 

It's definitely something I'd like to address, hopefully within the next few sprints.

**Comment by chanchancl** [comment]
@Arqu  Thanks for your help, I will close the issue.

**Comment by Arqu** [comment]
@chanchancl You're welcome, I've opened up the above tracker issue so we don't lose sight of it. I'll keep in mind to ping you back once it's implemented.
